# Generated by Django 4.2 on 2025-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=20)),
                ("pinyin", models.CharField(max_length=40)),
                ("tone", models.CharField(max_length=20)),
                ("meaning", models.CharField(max_length=40)),
                ("suffix", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
