# Generated by Django 5.1.7 on 2025-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('pinyin', models.CharField(max_length=40)),
                ('tone', models.IntegerField(default=0)),
                ('meaning', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
    ]
