# Generated by Django 4.2 on 2025-06-16 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "단어",
                "verbose_name_plural": "단어들",
            },
        ),
        migrations.AddField(
            model_name="word",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="생성일"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "쉬움"), ("medium", "보통"), ("hard", "어려움")],
                default="medium",
                max_length=10,
                verbose_name="난이도",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="example_sentence",
            field=models.TextField(blank=True, verbose_name="예문"),
        ),
        migrations.AddField(
            model_name="word",
            name="last_reviewed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 복습일"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="notes",
            field=models.TextField(blank=True, verbose_name="메모"),
        ),
        migrations.AddField(
            model_name="word",
            name="review_count",
            field=models.IntegerField(default=0, verbose_name="복습 횟수"),
        ),
        migrations.AddField(
            model_name="word",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="word",
            name="meaning",
            field=models.CharField(max_length=40, verbose_name="의미"),
        ),
        migrations.AlterField(
            model_name="word",
            name="pinyin",
            field=models.CharField(max_length=40, verbose_name="병음"),
        ),
        migrations.AlterField(
            model_name="word",
            name="suffix",
            field=models.CharField(blank=True, max_length=20, verbose_name="접미사"),
        ),
        migrations.AlterField(
            model_name="word",
            name="tone",
            field=models.CharField(max_length=20, verbose_name="성조"),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=20, verbose_name="단어"),
        ),
    ]
