# Generated by Django 4.2 on 2025-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_meaning_alter_word_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
