# Generated by Django 4.2 on 2025-06-16 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_alter_word_options_word_created_at_word_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="생성일"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "쉬움"), ("medium", "보통"), ("hard", "어려움")],
                db_index=True,
                default="medium",
                max_length=10,
                verbose_name="난이도",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="last_reviewed",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="마지막 복습일"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="meaning",
            field=models.CharField(db_index=True, max_length=40, verbose_name="의미"),
        ),
        migrations.AlterField(
            model_name="word",
            name="pinyin",
            field=models.CharField(db_index=True, max_length=40, verbose_name="병음"),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(db_index=True, max_length=20, verbose_name="단어"),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["word", "pinyin"], name="words_word_word_be17f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["difficulty", "review_count"],
                name="words_word_difficu_342896_idx",
            ),
        ),
    ]
