# Generated by Django 4.2 on 2025-07-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_alter_word_created_at_alter_word_difficulty_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_difficu_342896_idx",
        ),
        migrations.RemoveField(
            model_name="word",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="word",
            name="example_sentence",
        ),
        migrations.RemoveField(
            model_name="word",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="word",
            name="suffix",
        ),
    ]
