# Generated by Django 4.2 on 2025-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0004_remove_word_words_word_difficu_342896_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="word_class",
            field=models.CharField(
                choices=[
                    ("noun", "명사"),
                    ("pronoun", "대명사"),
                    ("verb", "동사"),
                    ("adjective", "형용사"),
                    ("numeral", "수사·양사"),
                    ("adverb", "부사"),
                    ("preposition", "개사·접속사·조사"),
                    ("interjection", "감탄사·의성·의태"),
                ],
                db_index=True,
                default="noun",
                max_length=20,
                verbose_name="품사",
            ),
        ),
    ]
