# Generated by Django 4.2 on 2025-09-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0005_word_word_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="last_reviewed",
        ),
        migrations.RemoveField(
            model_name="word",
            name="review_count",
        ),
    ]
