# Generated by Django 4.2 on 2026-01-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_word_meaning_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.CharField(db_index=True, max_length=255, verbose_name='의미'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pinyin',
            field=models.CharField(db_index=True, max_length=255, verbose_name='병음'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=100, verbose_name='단어'),
        ),
    ]
