# Generated by Django 4.2 on 2026-01-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_alter_word_meaning_alter_word_pinyin_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='tone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='성조'),
        ),
    ]
