# Generated by Django 5.2.17 on 2026-09-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0010_alter_word_tone"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="word",
            name="unique_word_word_class",
        ),
        migrations.AddField(
            model_name="word",
            name="language",
            field=models.CharField(
                choices=[("zh", "중국어"), ("en", "영어")],
                db_index=True,
                default="zh",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="pinyin",
            field=models.CharField(blank=True, max_length=255, verbose_name="병음"),
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(
                fields=("language", "word", "word_class"),
                name="unique_language_word_class",
            ),
        ),
    ]
