# Generated by Django 4.2 on 2025-04-23 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_word_suffix"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learning_since", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="words.word"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="learning",
            field=models.ManyToManyField(
                related_name="learned", through="accounts.LearningWord", to="words.word"
            ),
        ),
    ]
