# Generated by Django 4.2 on 2025-04-23 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_learningword_user_learning"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningword",
            name="to_be_revised",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
