# Generated by Django 4.2 on 2025-07-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_learningword_learning_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningword",
            name="correct_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="learningword",
            name="wrong_count",
            field=models.IntegerField(default=0),
        ),
    ]
