# Generated by Django 5.2.17 on 2026-09-29 08:31

from django.db import migrations, models


def merge_duplicate_learning_words(apps, schema_editor):
    """Keep shared words/logs; conservatively merge duplicate user-word links."""
    LearningWord = apps.get_model("accounts", "LearningWord")
    from django.db.models import Count

    database = schema_editor.connection.alias
    duplicates = (
        LearningWord.objects.using(database)
        .values("user_id", "word_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for pair in list(duplicates):
        rows = list(
            LearningWord.objects.using(database)
            .filter(user_id=pair["user_id"], word_id=pair["word_id"])
            .order_by("id")
        )
        keep = rows[0]
        for name in ["correct_count", "wrong_count", "no_of_revision"]:
            setattr(keep, name, sum(getattr(row, name) for row in rows))
        keep.learning_since = min(row.learning_since for row in rows)
        keep.last_time_revised = max(row.last_time_revised for row in rows)
        keep.to_be_revised = min(row.to_be_revised for row in rows)
        keep.learning_term = min(row.learning_term for row in rows)
        keep.save(using=database)
        LearningWord.objects.using(database).filter(
            pk__in=[row.pk for row in rows[1:]]
        ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_learningword_last_result_is_correct"),
        ("words", "0011_remove_word_unique_word_word_class_word_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="learningword",
            name="accepted_meanings",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="learningword",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="learningword",
            name="notes",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="learningword",
            name="personal_meaning",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="learningword",
            name="personal_pinyin",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="learningword",
            name="personal_tone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="learningword",
            name="tags",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="learningword",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studylog",
            name="corrected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studylog",
            name="previous_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studylog",
            name="request_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="studylog",
            name="response_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="learningword",
            name="no_of_revision",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="learningword",
            index=models.Index(
                fields=["user", "is_paused", "to_be_revised"], name="learning_due_idx"
            ),
        ),
        migrations.RunPython(merge_duplicate_learning_words, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="learningword",
            constraint=models.UniqueConstraint(
                fields=("user", "word"), name="unique_user_learning_word"
            ),
        ),
    ]
